language: python
python: 2.7
install: "conda install -c conda-forge lektor"
script:
- lektor build
- '[ "${TRAVIS_BRANCH}" = "source" ] && lektor deploy ghpages || false'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

notifications:
  email: false

