site: Bokeh Journal

ga_id: "UA-127553611-2"

future: true

collections:
  posts:
    output: true
    permalink: /posts/:slug

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

paginate: 6
paginate_path: "/posts/page:num/"

whitelist:
  - jekyll-redirect-from


